Add uncompressed sizes to table

diff --git a/.github/workflows/measure-disk-usage.yml b/.github/workflows/measure-disk-usage.yml
--- a/.github/workflows/measure-disk-usage.yml
+++ b/.github/workflows/measure-disk-usage.yml
@@ -138,21 +138,31 @@ jobs:
         set +e
 
         $cmd --compressed  --quality-gate-threshold ${{ vars.QUALITY_GATE_THRESHOLD_PERCENT }} 
-        exit_code=$?
+        exit_code_compressed=$?
+
+        $cmd --quality-gate-threshold ${{ vars.QUALITY_GATE_THRESHOLD_PERCENT }} 
+        exit_code_uncompressed=$?
 
         set -e
 
-        if [ $exit_code -eq 2 ]; then
-          echo "Quality gate threshold not passed"
-          echo "passed=false" >> "$GITHUB_OUTPUT"
-        elif [ $exit_code -eq 0 ]; then
-          echo "Quality gate passed"
-          echo "passed=true" >> "$GITHUB_OUTPUT"
-        else
-          exit $exit_code
+        if [ "$exit_code_compressed" -ne 0 ] && [ "$exit_code_compressed" -ne 2 ]; then
+          echo "Error: Compressed command failed with unexpected exit code: $exit_code_compressed"
+          exit "$exit_code_compressed"
         fi
 
-        $cmd 
+        if [ "$exit_code_uncompressed" -ne 0 ] && [ "$exit_code_uncompressed" -ne 2 ]; then
+          echo "Error: Uncompressed command failed with unexpected exit code: $exit_code_uncompressed"
+          exit "$exit_code_uncompressed"
+        fi
+
+        if [ "$exit_code_compressed" -eq 2 ] || [ "$exit_code_uncompressed" -eq 2 ]; then
+          echo "Quality gate threshold not passed"
+          echo "passed=false" >> "$GITHUB_OUTPUT"
+        else
+
+          echo "Quality gate passed"
+          echo "passed=true" >> "$GITHUB_OUTPUT"
+        fi
 
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
