Add format check to branch name

diff --git a/.github/workflows/measure-disk-usage.yml b/.github/workflows/measure-disk-usage.yml
--- a/.github/workflows/measure-disk-usage.yml
+++ b/.github/workflows/measure-disk-usage.yml
@@ -37,16 +37,23 @@ jobs:
 
     - name: Define command
       id: cmd
+      env:
+        HEAD_SHA: ${{ github.event.workflow_run.head_sha }}
+        EVENT_NAME: ${{ github.event.workflow_run.event }}
+        HEAD_BRANCH: ${{ github.event.workflow_run.head_branch }}
       run: |
-        cmd="ddev -v size status \
-        --commit ${{ github.event.workflow_run.head_sha }} \
-        --format json"
-
-        if [ "${{ github.event.workflow_run.event }}" = "push" ] && [ "${{ github.event.workflow_run.head_branch }}" = "master" ]; then 
-          cmd="$cmd --to-dd-key ${{ secrets.DD_API_KEY }}"
+        if ! [[ $HEAD_BRANCH =~ ^[A-Za-z0-9._/-]+$ ]]; then
+            echo "Branch name contains invalid characters. Exiting."
+            exit 1
         fi
 
+        cmd="ddev -v size status --commit \"$HEAD_SHA\" --format json"
+
+        if [ "$EVENT_NAME" = "push" ] && [ "$HEAD_BRANCH" = "master" ]; then 
+          cmd="$cmd --to-dd-key ${{ secrets.DD_API_KEY }}"
+        fi
         echo "cmd=$cmd" >> $GITHUB_OUTPUT
+    
 
     - name: Measure disk usage (Uncompressed)
       env:
