failing

diff --git a/.github/workflows/resolve-build-deps.yaml b/.github/workflows/resolve-build-deps.yaml
--- a/.github/workflows/resolve-build-deps.yaml
+++ b/.github/workflows/resolve-build-deps.yaml
@@ -261,6 +261,7 @@ jobs:
   calculate-size-diffs:
     needs: measure-disk-usage
     strategy:
+      fail-fast: false
       matrix:
         platform: [macos-x86_64, macos-aarch64] #, linux-x86_64, linux-aarch64, windows-x86_64]
     uses: ./.github/workflows/size-quality-gates.yml
@@ -268,17 +269,22 @@ jobs:
       platform: ${{ matrix.platform }}
       send_metrics: ${{ github.event_name == 'push' && github.ref_name == github.event.repository.default_branch }}
   
-  use-result-per-platform: 
+  check-all-quality-gates:
+    runs-on: ubuntu-latest
     needs: calculate-size-diffs
-    runs-on: ubuntu-22.04
-    strategy:
-      matrix:
-        platform: [macos-x86_64, macos-aarch64]
+    if: ${{ always() }} # Ensures this job runs even if a matrix job fails.
     steps:
-      - name: Gate per platform
-        run: echo "PASSES_QG=${{ fromJSON(needs.calculate-size-diffs.outputs.passes_qg) }}" /
-          echo "PASSES_QG=${{ needs.calculate-size-diffs.outputs.macos-x86_64.passes_qg }}"
-
+      - name: Check the outcome of all matrix jobs
+        run: |
+          # The 'needs' context provides a 'result' for the entire matrix.
+          # It will be 'success' only if ALL jobs in the matrix succeeded.
+          if [[ "${{ needs.calculate-size-diffs.result }}" == "success" ]]; then
+            echo "✨ All quality gates passed! The build is ready to be finalized."
+          else
+            echo "🛑 At least one quality gate failed. Failing the workflow."
+            exit 1
+          fi
+          
   comment-size-diffs-on-pr:
     needs:
       - calculate-size-diffs
