Avoid github action failure when no tests are selected for unit tests

diff --git a/.github/workflows/test-target.yml b/.github/workflows/test-target.yml
--- a/.github/workflows/test-target.yml
+++ b/.github/workflows/test-target.yml
@@ -213,37 +213,29 @@ jobs:
       env:
         DDEV_TEST_ENABLE_TRACING: "${{ inputs.repo == 'core' && '1' || '0' }}"
       run: |
-        if [ '${{ inputs.pytest-args }}' = '-m flaky' ]; then
-          set +e # Disable immediate exit
-          ddev test --cov --junit ${{ inputs.target }} -- -m unit ${{ inputs.pytest-args }}
-          exit_code=$?
-          if [ $exit_code -eq 5 ]; then
-            # Flaky test count can be zero, this is done to avoid pipeline failure
-            echo "No tests were collected."
-            exit 0
-          else
-            exit $exit_code
-          fi
+        set +e # Disable immediate exit
+        ddev test --cov --junit ${{ inputs.target }} -- -m unit ${{ inputs.pytest-args }}
+        exit_code=$?
+        if [ $exit_code -eq 5 ]; then
+          # Flaky test count can be zero, this is done to avoid pipeline failure
+          echo "No tests were collected."
+          exit 0
         else
-          ddev test --cov --junit ${{ inputs.target }}  -- -m unit ${{ inputs.pytest-args }}
+          exit $exit_code
         fi
 
     - name: Run Unit tests with minimum version of base package
       if: inputs.standard && inputs.minimum-base-package
       run: |
-        if [ '${{ inputs.pytest-args }}' = '-m flaky' ]; then
-          set +e # Disable immediate exit
-          ddev test --compat --recreate --junit ${{ inputs.target }} -- -m unit ${{ inputs.pytest-args }}
-          exit_code=$?
-          if [ $exit_code -eq 5 ]; then
-            # Flaky test count can be zero, this is done to avoid pipeline failure
-            echo "No tests were collected."
-            exit 0
-          else
-            exit $exit_code
-          fi
+        set +e # Disable immediate exit
+        ddev test --compat --recreate --junit ${{ inputs.target }} -- -m unit ${{ inputs.pytest-args }}
+        exit_code=$?
+        if [ $exit_code -eq 5 ]; then
+          # Flaky test count can be zero, this is done to avoid pipeline failure
+          echo "No tests were collected."
+          exit 0
         else
-          ddev test --compat --recreate --junit ${{ inputs.target }} -- -m unit ${{ inputs.pytest-args }}
+          exit $exit_code
         fi
 
     - name: Run E2E & Integration tests with latest base package
