Allow pytest to return success when no tests are collected for flaky test suite (#17990)
* Manage no tests collected exit code 5 from pytest for flaky test suite
* Manage passing additional -m arguments to pytest in e2e test
* Avoid passing `all` to pytest (revert to initial state)

diff --git a/.github/workflows/test-target.yml b/.github/workflows/test-target.yml
--- a/.github/workflows/test-target.yml
+++ b/.github/workflows/test-target.yml
@@ -212,23 +212,79 @@ jobs:
       if: inputs.standard && !inputs.minimum-base-package
       env:
         DDEV_TEST_ENABLE_TRACING: "${{ inputs.repo == 'core' && '1' || '0' }}"
-      run: ddev test --cov --junit ${{ inputs.target }} ${{ inputs.pytest-args != '' && format('-- {0}', inputs.pytest-args) || '' }}
+      run: |
+        if [ "${{ inputs.pytest-args }}" = "-m flaky" ]; then
+          set +e # Disable immediate exit
+          ddev test --cov --junit ${{ inputs.target }} -- ${{ inputs.pytest-args }}
+          exit_code=$?
+          if [ $exit_code -eq 5 ]; then
+            # Flaky test count can be zero, this is done to avoid pipeline failure
+            echo "No tests were collected."
+            exit 0
+          else
+            exit $exit_code
+          fi
+        else
+          ddev test --cov --junit ${{ inputs.target }} ${{ inputs.pytest-args != '' && format('-- {0}', inputs.pytest-args) || '' }}
+        fi
 
     - name: Run Unit & Integration tests with minimum version of base package
       if: inputs.standard && inputs.minimum-base-package
-      run: ddev test --compat --recreate --junit ${{ inputs.target }} ${{ inputs.pytest-args != '' && format('-- {0}', inputs.pytest-args) || '' }}
+      run: |
+        if [ "${{ inputs.pytest-args }}" = "-m flaky" ]; then
+          set +e # Disable immediate exit
+          ddev test --compat --recreate --junit ${{ inputs.target }} -- ${{ inputs.pytest-args }}
+          exit_code=$?
+          if [ $exit_code -eq 5 ]; then
+            # Flaky test count can be zero, this is done to avoid pipeline failure
+            echo "No tests were collected."
+            exit 0
+          else
+            exit $exit_code
+          fi
+        else
+          ddev test --compat --recreate --junit ${{ inputs.target }} ${{ inputs.pytest-args != '' && format('-- {0}', inputs.pytest-args) || '' }}
+        fi
 
     - name: Run E2E tests with latest base package
       if: inputs.standard && inputs.repo == 'core' && !inputs.minimum-base-package
       env:
         DD_API_KEY: "${{ secrets.DD_API_KEY }}"
-      run: ddev env test --base --new-env --junit ${{ inputs.target }} ${{ inputs.pytest-args != '' && format('-- all {0}', inputs.pytest-args) || '' }}
+      run: |
+        if [ "${{ inputs.pytest-args }}" = "-m flaky" ]; then
+          set +e # Disable immediate exit
+          ddev env test --base --new-env --junit ${{ inputs.target }} -- ${{ inputs.pytest-args }}
+          exit_code=$?
+          if [ $exit_code -eq 5 ]; then
+            # Flaky test count can be zero, this is done to avoid pipeline failure
+            echo "No tests were collected."
+            exit 0
+          else
+            exit $exit_code
+          fi
+        else
+          ddev env test --base --new-env --junit ${{ inputs.target }} ${{ inputs.pytest-args != '' && format('-- {0}', inputs.pytest-args) || '' }}
+        fi
 
     - name: Run E2E tests
       if: inputs.standard && inputs.repo != 'core'
       env:
         DD_API_KEY: "${{ secrets.DD_API_KEY }}"
-      run: ddev env test --new-env --junit ${{ inputs.target }} ${{ inputs.pytest-args != '' && format('-- all {0}', inputs.pytest-args) || '' }}
+      run: |
+        if [ "${{ inputs.pytest-args }}" = "-m flaky" ]; then
+          set +e # Disable immediate exit
+          ddev env test --new-env --junit ${{ inputs.target }} -- ${{ inputs.pytest-args }}
+          exit_code=$?
+          if [ $exit_code -eq 5 ]; then
+            # Flaky test count can be zero, this is done to avoid pipeline failure
+            echo "No tests were collected."
+            exit 0
+          else
+            exit $exit_code
+          fi
+        else
+          ddev env test --new-env --junit ${{ inputs.target }} ${{ inputs.pytest-args != '' && format('-- {0}', inputs.pytest-args) || '' }}
+        fi
 
     - name: Run benchmarks
       if: inputs.benchmark
@@ -243,7 +299,21 @@ jobs:
       env:
         DD_API_KEY: "${{ secrets.DD_API_KEY }}"
         DDEV_TEST_ENABLE_TRACING: "${{ inputs.repo == 'core' && '1' || '0' }}"
-      run: ddev env test --base --new-env --junit ${{ inputs.target }}:latest ${{ inputs.pytest-args != '' && format('-- all {0}', inputs.pytest-args) || '' }}
+      run: |
+        if [ "${{ inputs.pytest-args }}" = "-m flaky" ]; then
+          set +e # Disable immediate exit
+          ddev env test --base --new-env --junit ${{ inputs.target }}:latest -- ${{ inputs.pytest-args }}
+          exit_code=$?
+          if [ $exit_code -eq 5 ]; then
+            # Flaky test count can be zero, this is done to avoid pipeline failure
+            echo "No tests were collected."
+            exit 0
+          else
+            exit $exit_code
+          fi
+        else
+          ddev env test --base --new-env --junit ${{ inputs.target }}:latest ${{ inputs.pytest-args != '' && format('-- {0}', inputs.pytest-args) || '' }}
+        fi
 
     - name: View trace log
       if: inputs.repo == 'core' && always()
@@ -272,7 +342,12 @@ jobs:
         path: "${{ env.TEST_RESULTS_BASE_DIR }}"
 
     - name: Upload coverage data
-      if: inputs.standard && !github.event.repository.private && always()
+      if: >
+        inputs.standard && 
+        !github.event.repository.private && 
+        always() && 
+        inputs.pytest-args != '-m flaky'
+      # Flaky tests will have low coverage, don't upload it to avoid pipeline failure
       uses: codecov/codecov-action@v4
       with:
         token: ${{ secrets.CODECOV_TOKEN }}
