refactor test

diff --git a/.github/workflows/test-target.yml b/.github/workflows/test-target.yml
--- a/.github/workflows/test-target.yml
+++ b/.github/workflows/test-target.yml
@@ -274,30 +274,26 @@ jobs:
         #   ddev will interpret '-m' as an environment to run the e2e test on and fails
         # This is not required when no pytest args are provided and it will run all environments
         #   by default
+        set +e # Disable immediate exit
+
         if [ '${{ inputs.pytest-args }}' = '-m flaky' ]; then
-          set +e # Disable immediate exit
           ddev env test --base --new-env --junit ${{ inputs.target }} ${{ inputs.target-env || 'all' }} -- ${{ inputs.pytest-args }} -k "not fips"
           exit_code=$?
-          if [ $exit_code -eq 5 ]; then
-            # Flaky test count can be zero, this is done to avoid pipeline failure
-            echo "No tests were collected."
-            exit 0
-          else
-            exit $exit_code
-          fi
         elif [ '${{ inputs.pytest-args }}' = '-m "not flaky"' ]; then
-          set +e # Disable immediate exit
+          
           ddev env test --base --new-env --junit ${{ inputs.target }} ${{ inputs.target-env || 'all' }} -- ${{ inputs.pytest-args }} -k "not fips"
           exit_code=$?
-          if [ $exit_code -eq 5 ]; then
-            # Flaky test count can be zero, this is done to avoid pipeline failure
-            echo "No tests were collected."
-            exit 0
-          else
-            exit $exit_code
-          fi
         else
           ddev env test --base --new-env --junit ${{ inputs.target }} ${{ inputs.target-env || 'all' }} ${{ inputs.pytest-args != '' && format('-- {0} -k "not fips"', inputs.pytest-args) || '-- -k "not fips"' }}
+          exit_code=$?
+        fi
+        
+        if [ $exit_code -eq 5 ]; then
+          # Flaky test count can be zero, this is done to avoid pipeline failure
+          echo "No tests were collected."
+          exit 0
+        else
+          exit $exit_code
         fi
 
     - name: Run E2E tests
