Do not fail for -m "not flaky" if no tests are selected

diff --git a/.github/workflows/test-target.yml b/.github/workflows/test-target.yml
--- a/.github/workflows/test-target.yml
+++ b/.github/workflows/test-target.yml
@@ -269,6 +269,17 @@ jobs:
           else
             exit $exit_code
           fi
+        elif [ '${{ inputs.pytest-args }}' = '-m "not flaky"' ]; then
+          set +e # Disable immediate exit
+          ddev env test --base --new-env --junit ${{ inputs.target }} -- all ${{ inputs.pytest-args }}
+          exit_code=$?
+          if [ $exit_code -eq 5 ]; then
+            # Flaky test count can be zero, this is done to avoid pipeline failure
+            echo "No tests were collected."
+            exit 0
+          else
+            exit $exit_code
+          fi
         else
           ddev env test --base --new-env --junit ${{ inputs.target }} ${{ inputs.pytest-args != '' && format('-- all {0}', inputs.pytest-args) || '' }}
         fi
@@ -286,6 +297,17 @@ jobs:
         # This is not required when no pytest args are provided and it will run all environments
         #   by default
         if [ '${{ inputs.pytest-args }}' = '-m flaky' ]; then
+          set +e # Disable immediate exit
+          ddev env test --new-env --junit ${{ inputs.target }} -- all ${{ inputs.pytest-args }}
+          exit_code=$?
+          if [ $exit_code -eq 5 ]; then
+            # Flaky test count can be zero, this is done to avoid pipeline failure
+            echo "No tests were collected."
+            exit 0
+          else
+            exit $exit_code
+          fi
+        elif [ '${{ inputs.pytest-args }}' = '-m "not flaky"' ]; then
           set +e # Disable immediate exit
           ddev env test --new-env --junit ${{ inputs.target }} -- all ${{ inputs.pytest-args }}
           exit_code=$?
@@ -322,6 +344,17 @@ jobs:
         # This is not required when no pytest args are provided and it will run all environments
         #   by default
         if [ '${{ inputs.pytest-args }}' = '-m flaky' ]; then
+          set +e # Disable immediate exit
+          ddev env test --base --new-env --junit ${{ inputs.target }}:latest -- all ${{ inputs.pytest-args }}
+          exit_code=$?
+          if [ $exit_code -eq 5 ]; then
+            # Flaky test count can be zero, this is done to avoid pipeline failure
+            echo "No tests were collected."
+            exit 0
+          else
+            exit $exit_code
+          fi
+        elif [ '${{ inputs.pytest-args }}' = '-m "not flaky"' ]; then
           set +e # Disable immediate exit
           ddev env test --base --new-env --junit ${{ inputs.target }}:latest -- all ${{ inputs.pytest-args }}
           exit_code=$?
